### ISSUE TITLE
update shadowsocks

### ISSUE THREAD

**Issue by larryxiao625** [rssnsj/network-feeds#15]
文件该更新了最新的9011不能使用了root@Hiwifi:/tmp# opkg install shadowsocks-tools_1-20150108_ralink.ipk
Installing shadowsocks-tools (1-20150108) to root...
Collected errors:
- check_data_file_clashes: Package shadowsocks-tools wants to install file /usr/lib/lua/luci/controller/admin_web/index.lua
  But that file is already provided by package  \* twx
- check_data_file_clashes: Package shadowsocks-tools wants to install file /usr/lib/lua/luci/view/admin_web/menu/adv_menu.htm
  But that file is already provided by package  \* twx
- opkg_install_cmd: Cannot install package shadowsocks-tools.
  Installing shadowsocks-tools (1-20150108) to root...
  Collected errors:
- check_data_file_clashes: Package shadowsocks-tools wants to install file /usr/lib/lua/luci/controller/admin_web/index.lua
  But that file is already provided by package  \* twx
- check_data_file_clashes: Package shadowsocks-tools wants to install file /usr/lib/lua/luci/view/admin_web/menu/adv_menu.htm
  But that file is already provided by package  \* twx
- opkg_install_cmd: Cannot install package shadowsocks-tools.
  Installing shadowsocks-tools (1-20150108) to root...
  Collected errors:
- check_data_file_clashes: Package shadowsocks-tools wants to install file /usr/lib/lua/luci/controller/admin_web/index.lua
  But that file is already provided by package  \* twx
- check_data_file_clashes: Package shadowsocks-tools wants to install file /usr/lib/lua/luci/view/admin_web/menu/adv_menu.htm
  But that file is already provided by package  \* twx
- opkg_install_cmd: Cannot install package shadowsocks-tools.

**Comment by rssnsj** [comment]
请参考最新安装说明。
