### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by zwl2012** [rssnsj/network-feeds#16]
您好，首先很感谢您开发的插件,相较于其他的插件而言您的可以无缝的集成在系统内部，个人非常喜欢。另外请问下本插件有提供类似于白名单的功能吗？如果有的话，烦请告知。再次感谢您开发的插件，更要谢谢您。

**Comment by larryxiao625** [comment]
其实白名单就是自己把需要的域名加入gfw-list里面
