### ISSUE TITLE
安装教程建议加上pdnsd....

### ISSUE THREAD

**Issue by lialosiu** [rssnsj/network-feeds#17]
把包装上后发现gfwlist中的所有域名dns查询都失败

把 `/etc/init.d/ss-redir.sh` 中的所有 `2>dev/null` 都删掉后运行了下 `/etc/init.d/ss-redir.sh start`

才发现提示说：

```
/etc/rc.common: line 138: /etc/init.d/pdnsd: not found
```

我都忘记要依赖 pdnsd 了 _(:3」∠)_

建议安装那加上 opkg install pdnsd 吧……

**Comment by rssnsj** [comment]
多谢提醒！
