### ISSUE TITLE
极一无法安装

### ISSUE THREAD

**Issue by lantsing** [rssnsj/network-feeds#19]
极一（HC6361）运行命令
wget http://rssn.cn/roms/hifeeds/hiwifi-install.sh -q -O- | sh -
提示固件要升级到9011，天哪，极一官方最高版本才9008啊。
已经刷入http://rssn.cn/roms/uboot/里面的uboot，
如果要刷入预装插件的ROM，又应该如何操作？

**Comment by rssnsj** [comment]
手动改一下 /etc/.build 吧
