### ISSUE TITLE
ipset-lists 能否提供一种方式更新 china ip list?

### ISSUE THREAD

**Issue by pexcn** [rssnsj/network-feeds#32]
跟 ChinaDNS 类似 https://github.com/shadowsocks/ChinaDNS/blob/master/README.md#about-chnroute

**Comment by pexcn** [comment]
同样的，也希望能给一种更新 https://github.com/rssnsj/network-feeds/tree/master/ipset-lists/files/etc/gfwlist 这里面的文件的方式

**Comment by rssnsj** [comment]
在ipset-lists/tools下面，执行make即可。

 
—

同样的，也希望能给一种更新 https://github.com/rssnsj/network-feeds/tree/master/ipset-lists/files/etc/gfwlist 这里面的文件的方式

—

**Comment by pexcn** [comment]
感谢回复。
最好是能把那几个 shell 脚本内置到 ipk 里面，还有 china ip 的源，用 http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest 不是更准确点吗？

**Comment by pexcn** [comment]
噢⊙∀⊙！不好意思，看漏了，原来已经有 apnic 的数据了

**Comment by rssnsj** [comment]
> 噢⊙∀⊙！不好意思，看漏了，原来已经有 apnic 的数据了

对，是apnic的跟ipip.net合并的，因为会有一部分位于中国境内但分配自其他地区的IP。

**Comment by pexcn** [comment]
嗯。
再说回更新列表的问题，`cd ipset-lists/tools && make` 的方式会不会比较不够方便？
因为每次更新都需要新安装软件包，最好是能把 `ipv4_merger` 和那几个脚本，编译进 ipk, 以便能方便使用者随时更新，而不用重新编译~
