### ISSUE TITLE
来自 ipip 的 china list 结果不准确

### ISSUE THREAD

**Issue by pexcn** [rssnsj/network-feeds#34]
我尝试移除了 ipip 的结果：https://github.com/pexcn/network-feeds/commit/0a9167db824c51934c7889222296efbdbe864c8a

查了它的几个 IP, 有的来源是美国/香港/澳大利亚.....

参考：
https://bgp.he.net/ip/20.139.160.1#_whois
http://ip-api.com/#20.134.160.1

https://bgp.he.net/ip/40.0.247.0#_whois
http://ip-api.com/#40.0.247.0

**Comment by paulgao** [comment]
哪里不准确呢？
我们确认过 20.134.160.0/20 和 20.139.160.0/20 都是在天津电信。
40.0.247.0/24 和 40.0.248.0/21 都在上海电信。
所在公告 AS 也都是可信的，不是滥用行为。

您再仔细看看吧，但是就别拿别的库的结果说事了。您发起个 traceroute 都比这有效力。

**Comment by pexcn** [comment]
好吧，果然是天津的，但是为什么 bgp.he.net 的显示美国？这种数据的原始来源是从哪里看的？

**Comment by paulgao** [comment]
那个应该是根据 WHOIS 信息里面的国家标志显示的，你以后可以忽略。：）

**Comment by pexcn** [comment]
好的，感谢解答。
我也找到了，应该是在 http://wq.apnic.net/static/search.html 查询的，不知道为什么查询的 `20.134.160.0/20` 显示的 Country 是 US 而不是 CN...

**Comment by paulgao** [comment]
方便的话可以加个微信，有问题可以可以直接问我。

**Comment by pexcn** [comment]
还是用 telegram 吧，id 和我 github id 一样 :)

**Comment by paulgao** [comment]
好的。明天加。

**Comment by pexcn** [comment]
:D
