### ISSUE TITLE
想集成到自己编译的固件里，怎么操作？

### ISSUE THREAD

**Issue by lantsing** [rssnsj/network-feeds#5]
有git源么？谢谢。

**Comment by lialosiu** [comment]
直接 `git clone` 这个库到 `package/` 下面就好
还要把这 [10,11,12 patch](https://github.com/rssnsj/openwrt-hc5761/tree/master/patches) 给打上
`make menuconfig` 时， `network` 下面， `shadowsocks-tools` 选上， `Web Servers/Proxies` 里面的 `pdnsd` 选上

**Comment by lantsing** [comment]
菜鸟初学，是这样么？
git clone https://github.com/rssnsj/network-feeds package/
补丁怎么打？

**Comment by rssnsj** [comment]
请参考openwrt-hc5761项目的Makefile：
https://github.com/rssnsj/openwrt-hc5761/blob/master/Makefile#L25
