### ISSUE TITLE
/usr/lib/lua/luci/controller/admin_web/index.lua在0.9010需要更新

### ISSUE THREAD

**Issue by AnyoeDove** [rssnsj/network-feeds#9]
```
entry({"admin_web", "network","devices_list"}, template("admin_web/network/devices_list"), _("链接设备列表"), 200)
```

后面需要添加：
    entry({"admin_web", "network","devices_offline_list"}, template("admin_web/network/devices_offline_list"), _("历史连接设备列表"), 200)
    entry({"admin_web", "network","devices_black_list"}, template("admin_web/network/devices_black_list"), _("黑名单设备列表"), 200)

另外【链接设备列表】应该是【连接设备列表】吧

**Comment by AnyoeDove** [comment]
entry({"admin_web", "network","devices_list"}, template("admin_web/network/devices_list"), _("链接设备列表"), 200)
后面需要添加：
	entry({"admin_web", "network","devices_offline_list"}, template("admin_web/network/devices_offline_list"), _("历史连接设备列表"), 200)
	entry({"admin_web", "network","devices_black_list"}, template("admin_web/network/devices_black_list"), _("黑名单设备列表"), 200)

另外【链接设备列表】应该是【连接设备列表】吧

**Comment by rssnsj** [comment]
谢谢，已经更新为极路由9012版本
